# Generated by Django 5.0.3 on 2026-04-03 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('remaining_quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('maker_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maker_trades', to='matching_engine.order')),
                ('taker_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker_trades', to='matching_engine.order')),
            ],
        ),
    ]
