# Generated by Django 5.0.3 on 2026-04-03 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
